config/routes.rb
Rails.application.routes.draw do

  get 'reviews/index'
  root to: 'users#show'

  devise_for :users
  get 'homes/top' => "homes#top"

  resource :user, except: [:new, :create, :destroy]
  resources :movies do
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:index, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  
  validates_uniqueness_of :movie_id, scope: :user_id
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :image
   
  with_options presence: true do
    validates :title
    validates :body
  end
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :movies, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :image

  def already_favorited?(movie)
    self.favorites.exists?(movie_id: movie.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path
  end
  
  def after_sign_up_path_for(resource)
    user_path
  end
  
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.create(movie_id: params[:movie_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @favorite = current_user.favorites.find_by(movie_id: @movie.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    # @review = Review.new
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user_id = current_user.id
    if @movie.save
      redirect_to movie_path(@movie), notice: "投稿に成功しました。"
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
    if @movie.user_id != current_user.id
      redirect_to movie_path, alert: "不正なアクセスです。"
    end
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      flash[:notice] = "更新しました！"
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    movie = Movie.find(params[:id])
    movie.destroy
    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :body, :image, :star)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to ramen_shop_reviews_path(@review.movie)
    else
      @movie = Movie.find(params[:movie_id])
      render "movies/show"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました！"
      redirect_to user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="top col-md-12">
      <h1>
        映画は人生だ！！
      </h1>
      <p>
        映画は人生を豊かにしてくれます。その感動は面白さを、他人と共有することで、さらに人生は豊かになると思っています。<br>
        コメディでも、ファンタジーでも、サスペンスでも、ジャンルを問わず、皆さんの好きな映画を共有してください。
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/dcb93b80d0.js" crossorigin="anonymous"></script>
  </head>

  <body class="bg">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'moviegram', root_path, class: "navbar-brand" %>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="Navber">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "ABOUT", homes_top_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ", user_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規投稿", new_movie_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", movies_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% else %>
        <div class="collapse navbar-collapse" id="Navber">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% end %>
    </nav>
    <% if flash[:notice] %>
      <div class="alert alert-primary" role="alert"><strong><%= notice %></strong></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-primary" role="alert"><strong><%= notice %></strong></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/movies/_error.html.erb
<% if movie.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(movie.errors.count, "error") %></h4>
    <p><%= pluralize(movie.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

app/views/movies/_form.html.erb
<%= form_for movie do |f| %>
 <div class="form-group">
 <label>映画名</label>
  <%= f.text_field :title, class: "form-control" %>
 </div>

  <div class="form-group">
   <label>感想</label>
   <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
   <label>画像</label>
   <%= f.file_field :image, accept: "image/*" %>
  </div>

  <div id="evaluate_stars">
    <label style="margin-right: 2px; margin-bottom: 24px; color: white;">評価</label>
  </div>

<%= f.submit class: "btn btn-success" %>

<!--星レビュー機能-->

<script>
  $('#evaluate_stars').raty({
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    scoreName: 'movie[star]' //登録するモデル名とカラム名を記述
  });
</script>

<!--ここまで-->

<% end %>

app/views/movies/edit.html.erb
<%= render 'error', movie: @movie %>
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>編集</h2>
      <%= render 'form', movie: @movie %>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="cards row gx-4 gx-lg-5 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <% @movies.each do |movie| %>
      <div class="whole-card mb-5 col-12 ml-2">
       <div class="card h-100">
        <div class="card-image" style="text-align: center">
          <% if movie.image.attached? %>
            <%= image_tag movie.image, class: "movie_icon" %>
          <% else %>
            <%= image_tag 'no_image', class: "movie_icon" %>
          <% end %>
        </div>
        <div class="card-body p-4">
          <div class="text-center">
            <h5 class="card-title"><%= link_to movie.title, movie_path(movie) %></h5>
            <h6 class="user_name">投稿者：<%= movie.user.name %></h6>
            <p class="card-text"><%= movie.body %></p>
            <div>
              <% if current_user.already_favorited?(movie) %>
                <%= link_to movie_favorites_path(movie), method: :delete do %>
                  <i class="fas fa-heart"></i>
                <% end %>
              <% else %>
                <%= link_to movie_favorites_path(movie), method: :post do %>
                  <i class="far fa-heart"></i>
                <% end %>
              <% end %>
              <%= movie.favorites.count %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
   </div>
  </div>
</section>

app/views/movies/new.html.erb
<%= render 'error', movie: @movie %>
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2 class="title">新規投稿</h2>
      <%= render 'form', movie: @movie %>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= @movie.title %></h5>
          <p>画像</p>
            <% if @movie.image.attached? %>
              <%= image_tag @movie.image, class: "movie_icon" %>
            <% else %>
              <%= image_tag 'no_image', class: "movie_icon" %>
            <% end %>
          <p class="card-text"><%= simple_format @movie.body %></p>
          <p class="card-text">
            <small class="text-muted">更新日：<%= @movie.updated_at.strftime("%Y-%m-%d") %></small>
          </p>
          <% if current_user.already_favorited?(@movie) %>
            <%= link_to movie_favorites_path(@movie), method: :delete do %>
              <i class="fas fa-heart"></i>
            <% end %>
          <% else %>
            <%= link_to movie_favorites_path(@movie), method: :post do %>
              <i class="far fa-heart"></i>
            <% end %>
          <% end %>
          <%= @movie.favorites.count %>
          <% if @movie.user == current_user %>
            <%= link_to '編集', edit_movie_path(@movie), class: "btn btn-success" %>
            <%= link_to '削除', movie_path(@movie), method: :delete, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<p class="is-size-4 mb-3">レビューを書く</p>

<div class="rating-box mt-3">
  <%= form_with model: review, url: movie_reviews_path(movie), local: true do |f| %>
    <div class="main-rating">
      <div class="ratings mb-3">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class="ml-3 rating-value-display"><span id="rating-value-display">0</span>5</div>
    </div>
    <%= f.hidden_field :movie_id, id: "movie.id" %>
    <%= f.hidden_field :score, id: "rating-value" %>
    <%= f.text_field :content, class: "textarea" %>
    <%= f.submit "保存", class: "button mt-3" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(@user.errors.count, "error") %></h4>
    <p><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>編集</h2>
      <%= form_for @user do |f| %>
        <label>ユーザー名</label>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <label>メールアドレス</label>
        <div class="form-group">
          <%= f.text_field :email, class: "form-control" %>
        </div>
        <label>プロフィール画像</label>
        <div class="form-group">
          <%= f.file_field :image, accept: "image/*" %>
        </div>
        <div>
          <%= f.submit class: "btn btn-success" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-7 mx-auto">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= current_user.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= current_user.email %></h6>
            <% if current_user.image.attached? %>
              <%= image_tag current_user.image, class: "icon" %>
            <% else %>
              <%= image_tag 'no_image', size: "100×100" %>
            <% end %>
          <%= link_to "ユーザー編集", edit_user_path %>
        </div>
      </div>
    </div>
  </div>
</div>